spring:
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    #url: jdbc:mysql://127.0.0.1:3306/accounts-service-db
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${dh.keycloak.clientId}
            client-secret: ${dh.keycloak.clientSecret}
            scope: openid
            realm: ${dh.keycloak.realm}
            serverUrl: ${dh.keycloak.serverUrl}
        provider:
          keycloak:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
        resourceserver:
          jwt:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
            jwk-set-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/certs

dh:
  keycloak:
    realm: dh-money-users
    serverUrl: http://keycloak:8080
    clientId: api-dh-money
    clientSecret: 2bgKXNvbhtpbEUux2QmNfUev6D5hzqA4
    tokenEndpoint: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/token
    
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: accounts-service
    description: microservicio de administracion de billetera virtual (remoto)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8082/actuator/info
    healthCheckUrlPath: http://localhost:8082/actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8082
